"""empty message

Revision ID: c8647f504c1a
Revises: 
Create Date: 2026-10-07 02:58:10.564688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app
from app.application.enums import EventTypeEnum, CurrencyEnum, PaymentStatusEnum

# revision identifiers, used by Alembic.
revision: str = 'c8647f504c1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('event_type', app.infrastructure.db.core.custom_types.EnumString(EventTypeEnum), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("event_type IN ('payment.created')", name='ck_outbox_events_event_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_events_processed_at_event_type_created_at', 'outbox_events', ['processed_at', 'event_type', 'created_at'], unique=False, postgresql_where=sa.text('processed_at IS NULL'))
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('currency', app.infrastructure.db.core.custom_types.EnumString(CurrencyEnum), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=False),
    sa.Column('status', app.infrastructure.db.core.custom_types.EnumString(PaymentStatusEnum), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("currency IN ('RUB','USD','EUR')", name='ck_payments_currency'),
    sa.CheckConstraint("status IN ('pending','succeeded','failed')", name='ck_payments_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_idempotency_key', 'payments', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_idempotency_key', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_outbox_events_processed_at_event_type_created_at', table_name='outbox_events', postgresql_where=sa.text('processed_at IS NULL'))
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
